[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs-cli --chip RP2040 --speed 200"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"

[unstable]
build-std = ["core", "panic_abort", "alloc"]
build-std-features = ["optimize_for_size", "panic_immediate_abort", "core/turbowakers"]
