[package]
name = "rusty-dilemma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "left"
path = "src/bin/left.rs"

[[bin]]
name = "right"
path = "src/bin/right.rs"

[dependencies]
shared = { path = "../shared" }
embassy-embedded-hal = { git = "https://github.com/simmsb/embassy" }
embassy-executor = { git = "https://github.com/simmsb/embassy", features = ["arch-cortex-m", "executor-thread", "integrated-timers", "nightly"] }
embassy-futures = { git = "https://github.com/simmsb/embassy" }
embassy-rp = { git = "https://github.com/simmsb/embassy", default-features = false, features = ["unstable-pac", "time-driver", "unstable-traits", "nightly"] }
embassy-sync = { git = "https://github.com/simmsb/embassy", features = ["nightly"] }
embassy-time = { git = "https://github.com/simmsb/embassy" }
embassy-usb = { git = "https://github.com/simmsb/embassy" }
embassy-boot-rp = { git = "https://github.com/simmsb/embassy", optional = true, features = ["nightly"] }

cortex-m = { version = "0.7.7", features = ["critical-section-single-core", "inline-asm"] }
cortex-m-rt = "0.7.3"
panic-reset = "0.1.1"
futures = { version = "0.3.28", default-features = false, features = ["async-await", "cfg-target-has-atomic", "unstable"] }
byte-slice-cast = { version = "1.2.2", default-features = false }
embedded-hal-1 = { package = "embedded-hal", version = "1.0.0-alpha.10" }
embedded-hal-async = "0.2.0-alpha.1"
embedded-io = { version = "0.4.0", features = ["async"] }
static_cell = "1.0.0"
log_log = { package = "log", version = "0.4.17" }
pio-proc = "0.2.2"
pio = "0.2.1"
heapless = "0.7.16"
usbd-hid = "0.6.1"
postcard = "1.0.4"
serde = { version = "1.0.160", default-features = false, features = ["derive"] }
once_cell = { version = "1.17.1", features = ["atomic-polyfill"], default-features = false }
atomic-polyfill = "1.0.2"
bbqueue = { version = "0.5.1", features = ["cortex-m", "thumbv6"] }
panic-probe = { version = "0.3.1", optional = true }
defmt = { version = "=0.3.2", optional = true }
defmt-rtt = { version = "0.4.0", optional = true }
bitfield-struct = "0.4.1"
num_enum = { version = "0.6.1", default-features = false }
num = { version = "0.4.0", default-features = false }
usbd-human-interface-device = "0.4.1"

[features]
probe = ["defmt", "defmt-rtt", "panic-probe", "shared/defmt", "embassy-embedded-hal/defmt", "embassy-sync/defmt", "embassy-executor/defmt", "embassy-time/defmt", "embassy-time/defmt-timestamp-uptime", "embassy-rp/defmt", "embassy-usb/defmt", "postcard/use-defmt"]
bootloader = ["embassy-boot-rp"]
default = ["probe"]
